export const COLORS = {
  background: '#0d0c0a',
  cream: '#f0ede4',
  blue: '#2a2eef',
  cardSurface: 'rgba(22,21,19,0.88)',
  white: '#ffffff',
  darkText: '#1a1918',
  muted: 'rgba(240,237,228,0.5)',
  border: 'rgba(240,237,228,0.12)',
  chipBg: 'rgba(240,237,228,0.15)',
};

export const SUPABASE_URL = 'https://tzpbdfdhmbvaoexwgobi.supabase.co';
export const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cGJkZmRobWJ2YW9leHdnb2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMjA0MzUsImV4cCI6MjA5MTc5NjQzNX0.1Cpx_lJB-Xvnc5Olbu3wfQgwd2N-bJVB1DdOH3RX0x8';
export const GOOGLE_MAPS_API_KEY = 'AIzaSyDKPS1qgKmSogsEV2g4MJarBY6bmy2oLM8';

export const NEIGHBORHOODS = [
  'Wynwood',
  'Brickell',
  'South Beach',
  'Little Havana',
  'Design District',
  'Midtown',
  'Coconut Grove',
  'Coral Gables',
  'Little Haiti',
  'Downtown',
];

export const VENUE_TYPES = [
  'Bar',
  'Nightclub',
  'Restaurant',
  'Lounge',
  'Rooftop',
  'Live Music',
  'Sports Bar',
  'Dive Bar',
];

export const AVATAR_COLORS = [
  '#2a2eef',
  '#ef2a6a',
  '#2aef9e',
  '#efb82a',
  '#9e2aef',
  '#2aadef',
  '#ef6b2a',
  '#2aef4a',
];

export const VIBES = [
  'Low-key',
  'High energy',
  'Moody lighting',
  'Outdoor vibes',
  'Dance floor',
  'Rooftop views',
  'Live music',
  'Craft cocktails',
  'Sports on TV',
  'Late night',
  'Date night',
  'Group hangout',
];

export const MOCK_VENUES = [
  {
    id: '1',
    name: 'LIV Miami',
    type: 'Nightclub',
    neighborhood: 'South Beach',
    address: '4441 Collins Ave, Miami Beach, FL 33140',
    crowd: 92,
    wait: 25,
    rating: 4.3,
    lat: 25.8145,
    lng: -80.1201,
    image: 'https://picsum.photos/seed/liv/800/500',
    hours: 'Thu–Sun 11pm–5am',
    priceLevel: 4,
  },
  {
    id: '2',
    name: 'The Broken Shaker',
    type: 'Bar',
    neighborhood: 'South Beach',
    address: '2727 Indian Creek Dr, Miami Beach, FL 33140',
    crowd: 68,
    wait: 0,
    rating: 4.6,
    lat: 25.8011,
    lng: -80.1318,
    image: 'https://picsum.photos/seed/shaker/800/500',
    hours: 'Daily 6pm–2am',
    priceLevel: 3,
  },
  {
    id: '3',
    name: 'Wynwood Brewing',
    type: 'Bar',
    neighborhood: 'Wynwood',
    address: '565 NW 24th St, Miami, FL 33127',
    crowd: 55,
    wait: 0,
    rating: 4.5,
    lat: 25.8027,
    lng: -80.1994,
    image: 'https://picsum.photos/seed/wynwood/800/500',
    hours: 'Mon–Thu 4pm–12am, Fri–Sun 12pm–2am',
    priceLevel: 2,
  },
  {
    id: '4',
    name: 'Ball & Chain',
    type: 'Live Music',
    neighborhood: 'Little Havana',
    address: '1513 SW 8th St, Miami, FL 33135',
    crowd: 78,
    wait: 10,
    rating: 4.4,
    lat: 25.7686,
    lng: -80.2132,
    image: 'https://picsum.photos/seed/ball/800/500',
    hours: 'Daily 5pm–3am',
    priceLevel: 2,
  },
  {
    id: '5',
    name: 'Sugar (East Hotel)',
    type: 'Rooftop',
    neighborhood: 'Brickell',
    address: '788 Brickell Plaza, Miami, FL 33131',
    crowd: 80,
    wait: 15,
    rating: 4.5,
    lat: 25.7617,
    lng: -80.1918,
    image: 'https://picsum.photos/seed/sugar/800/500',
    hours: 'Daily 5pm–2am',
    priceLevel: 3,
  },
  {
    id: '6',
    name: 'E11EVEN Miami',
    type: 'Nightclub',
    neighborhood: 'Downtown',
    address: '29 NE 11th St, Miami, FL 33132',
    crowd: 95,
    wait: 30,
    rating: 4.2,
    lat: 25.7779,
    lng: -80.1939,
    image: 'https://picsum.photos/seed/eleven/800/500',
    hours: '24 hours',
    priceLevel: 4,
  },
  {
    id: '7',
    name: 'Kiki on the River',
    type: 'Restaurant',
    neighborhood: 'Wynwood',
    address: '450 NW North River Dr, Miami, FL 33128',
    crowd: 70,
    wait: 20,
    rating: 4.4,
    lat: 25.7824,
    lng: -80.2048,
    image: 'https://picsum.photos/seed/kiki/800/500',
    hours: 'Daily 6pm–2am',
    priceLevel: 3,
  },
  {
    id: '8',
    name: 'Basement Miami',
    type: 'Nightclub',
    neighborhood: 'South Beach',
    address: '2901 Collins Ave, Miami Beach, FL 33140',
    crowd: 85,
    wait: 20,
    rating: 4.1,
    lat: 25.8106,
    lng: -80.1225,
    image: 'https://picsum.photos/seed/basement/800/500',
    hours: 'Fri–Sat 11pm–5am',
    priceLevel: 3,
  },
];
